### PR TITLE
Update set.xml

### PR DESCRIPTION
**Pull request by xicidis**
Updated a Typo

### CODE REVIEW

**Comment by kellyelton** [comment]
Refresh my memory, are you still waiting for me to update the feed again or is the game good now?

**Comment by xicidis** [comment]
I've got a small list of things to edit, but I'll be doing it the way you
told me to do it. I just need to update it, and push it to the servers and
someone will find it and approve it, correct?

**Comment by kellyelton** [comment]
Right. If you do a pull request to this repository I'll see it right away

**Comment by xicidis** [comment]
Hello again!

I sent in a bunch of updates. I edited the Changelog and added comments to
the pull requests so you can see what it is. I tried to add a new folder,
but it says "Uploads are disabled. File uploads require push access to this
repository."

So, here is the small set of Champion Promos included.

Thanks for the help again!

Michael

**Comment by brine** [comment]
When you open up a pull request, you can make additional commits to that branch and it'll automatically add those commits to your pull request.  You wont need to open up a new request each time you make a change

**Comment by xicidis** [comment]
Oh ok. I'll do that next time. Sorry about that.

**Comment by xicidis** [comment]
Howdy. I tried to do a pull request for the set of champion cards and it
hasn't gone through yet. Did I do something wrong with it?

Thanks!
Michael

**Comment by kellyelton** [comment]
No, I just haven't got a chance to go through it yet. I'll be going through them all at some point today.

**Pull request merged**
