### PR TITLE
New Street Fighter Set

### PR DESCRIPTION
**Pull request by xicidis**

### CODE REVIEW

**Comment by xicidis** [comment]
Thanks a ton for merging it so quickly!
It should be up in the next week or so, correct? We can't wait to start
testing out the new stuff.
Thanks for all of your hard work!

Michael

**Comment by kellyelton** [comment]
I'm still waiting on a fix for this

**Comment by xicidis** [comment]
A fix from me? Or internally?

**Comment by brine** [comment]
Yeah it just needs a new commit to fix the GUID issue

**Comment by xicidis** [comment]
What guid issue?

**Comment by kellyelton** [comment]
```The guid for Rolling Attack is not a proper guid. That needs to be fixed, and anything referencing that guid needs to be fixed before I can release this.```

**Comment by xicidis** [comment]
I've fixed it and sent it live

**Pull request merged**
