### PR TITLE
Add new set to OCTGN- Blood Omen

### PR DESCRIPTION
**Pull request by xicidis**
New Set for UFS

### CODE REVIEW

**Comment by xicidis** [comment]
Thank you

**Comment by xicidis** [comment]
Sorry to bother you. The files were merged, but when I load up OCTGN, it
doesn't find an update. Does it just take a few days for it to update?

Thanks,
Michael

**Comment by brine** [comment]
Merging into github repos won't auto-update the plugin in OCTGN.  It still needs to be pulled locally, compiled via o8build, then uploaded to the myget feed.

**Comment by kellyelton** [comment]
I'll take care of that today

**Comment by xicidis** [comment]
Oooooo
Ok  I get it.
I thought I did something wrong again and was confused.
Thanks again!

On Dec 10, 2016 7:50 AM, "Kelly Elton" <notifications@github.com> wrote:

I'll take care of that today

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/octgn/OCTGN-UFS/pull/10#issuecomment-266217451>, or mute
the thread

**Comment by kellyelton** [comment]
Alright I've uploaded it. It should be live in a few minutes. Sorry about the delay.

**Pull request merged**
