### PR TITLE
Adding Champion Promos3

### PR DESCRIPTION
**Pull request by xicidis**
This is all of the cards for the champion promos 3 set

### CODE REVIEW

**Comment by brine** [comment]
what's the purpose of the blanktextfile?

**Comment by xicidis** [comment]
I couldn't add the cards folder without putting something there. Is there a
better way?

**Comment by brine** [comment]
you don't actually need the cards folder

**Comment by xicidis** [comment]
Ah. Ok. Should I delete the folder and repush?

**Comment by brine** [comment]
if you commit to your local branch it'll automatically update this pull request

**Comment by xicidis** [comment]
OK. Done. How is that? If it works properly I have a new set to add ASAP. I just wanted to make sure I added this properly this time before I sent the next.
Thanks!

**Comment by brine** [comment]
Yeah go ahead

**Comment by xicidis** [comment]
Can you please update this asap Brine? Or let me know if there's a problem as soon as you can? Thank you.

**Comment by brine** [comment]
I don't have access to this feed, kelly would need to handle it I believe

**Comment by brine** [comment]
do none of the sets for the game use line breaks in the card rules text?

**Comment by xicidis** [comment]
There's too much text on a lot of them. We also have access to the images for everything readily available thanks to Jasco.

**Pull request merged**
